#include "stm32f1xx_hal.h"
#include "ili9488.h"
#include "lcd_io_spi.h"
#include "main_window.h"
#include "main.h"
#include "lcd.h"
#include "u8g.h"
#include "lcd.h"

/* BSP_LCD_... */
#include "stm32_adafruit_lcd.h"
extern const u8g_fntpgm_uint8_t rus10x20[2863];
extern LCD_DrawPropTypeDef DrawProp;

uint32_t my_min, my_max, my_addr;
uint8_t is_uniq;
extern uint32_t log_memory_buf [LOG_ENTRY_SIZE];

extern uint16_t rus_font_color;

uint32_t read_buf [LOG_ENTRY_SIZE];

uint8_t string_buf[40];

const char no_logs[12]  = {157, 181, 130, 32, 183, 176, 191, 184, 129, 181, 185 ,0}; //Нет записей (autogenerated by ru_str_converter.py script)
const char header1[25] = {151, 176, 191, 184, 129, 140, 32, 189, 190, 188, 181, 128, 32, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 46 ,0}; //Запись номер 0000000000. (autogenerated by ru_str_converter.py script)
const char header2[31] = {156, 176, 186, 129, 184, 188, 176, 187, 140, 189, 139, 185, 32, 189, 190, 188, 181, 128, 32, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 46 ,0}; //Максимальный номер 0000000000. (autogenerated by ru_str_converter.py script)
const char header3[29] = {146, 129, 181, 179, 190, 32, 129, 190, 133, 128, 176, 189, 181, 189, 190, 32, 48, 48, 48, 32, 183, 176, 191, 184, 129, 181, 185, 46 ,0}; //Всего сохранено 000 записей. (autogenerated by ru_str_converter.py script)
const char alrm1[] = {145, 176, 130, 176, 128, 181, 143, 32, 128, 176, 183, 128, 143, 182, 181, 189, 176, 33 ,0}; //Батарея разряжена! (autogenerated by ru_str_converter.py script)
const char alrm2[] = {145, 176, 130, 176, 128, 181, 143, 32, 178, 32, 191, 190, 128, 143, 180, 186, 181, 46 ,0}; //Батарея в порядке. (autogenerated by ru_str_converter.py script)
const char alrm3[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 186, 190, 189, 134, 181, 189, 130, 128, 176, 130, 190, 128, 176, 47, 148, 140, 142, 176, 128, 176, 32, 191, 128, 181, 178, 139, 136, 181, 189, 190, 33 ,0}; //Давление концентратора/Дьюара превышено! (autogenerated by ru_str_converter.py script)
const char alrm4[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 186, 190, 189, 134, 181, 189, 130, 128, 176, 130, 190, 128, 176, 47, 148, 140, 142, 176, 128, 176, 32, 189, 181, 32, 191, 128, 181, 178, 139, 136, 181, 189, 190, 46 ,0}; //Давление концентратора/Дьюара не превышено. (autogenerated by ru_str_converter.py script)
const char alrm5[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 186, 190, 189, 134, 181, 189, 130, 128, 176, 130, 190, 128, 176, 47, 148, 140, 142, 176, 128, 176, 32, 189, 181, 180, 190, 129, 130, 176, 130, 190, 135, 189, 190, 33 ,0}; //Давление концентратора/Дьюара недостаточно! (autogenerated by ru_str_converter.py script)
const char alrm6[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 186, 190, 189, 134, 181, 189, 130, 128, 176, 130, 190, 128, 176, 47, 148, 140, 142, 176, 128, 176, 32, 178, 139, 136, 181, 32, 188, 184, 189, 184, 188, 131, 188, 176, 46 ,0}; //Давление концентратора/Дьюара выше минимума. (autogenerated by ru_str_converter.py script)
const char alrm7[] = {157, 131, 182, 189, 190, 32, 183, 176, 188, 181, 189, 184, 130, 140, 32, 177, 176, 187, 187, 190, 189, 139, 33 ,0}; //Нужно заменить баллоны! (autogenerated by ru_str_converter.py script)
const char alrm8[] = {147, 176, 183, 176, 32, 178, 32, 177, 176, 187, 187, 190, 189, 176, 133, 32, 181, 137, 181, 32, 180, 190, 129, 130, 176, 130, 190, 135, 189, 190, 46 ,0}; //Газа в баллонах ещё достаточно. (autogenerated by ru_str_converter.py script)
const char alrm9[] = {161, 184, 129, 130, 181, 188, 176, 32, 191, 181, 128, 181, 136, 187, 176, 32, 178, 32, 176, 178, 176, 128, 184, 185, 189, 139, 185, 32, 128, 181, 182, 184, 188, 33 ,0}; //Система перешла в аварийный режим! (autogenerated by ru_str_converter.py script)
const char alrm10[] = {161, 184, 129, 130, 181, 188, 176, 32, 178, 32, 136, 130, 176, 130, 189, 190, 188, 32, 128, 181, 182, 184, 188, 181, 46 ,0}; //Система в штатном режиме. (autogenerated by ru_str_converter.py script)
const char alrm11[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 178, 32, 187, 184, 189, 184, 184, 32, 191, 128, 181, 178, 139, 136, 181, 189, 190, 33 ,0}; //Давление в линии превышено! (autogenerated by ru_str_converter.py script)
const char alrm12[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 178, 32, 187, 184, 189, 184, 184, 32, 189, 181, 32, 191, 128, 181, 178, 139, 136, 181, 189, 190, 46 ,0}; //Давление в линии не превышено. (autogenerated by ru_str_converter.py script)
const char alrm13[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 178, 32, 187, 184, 189, 184, 184, 32, 131, 191, 176, 187, 190, 32, 189, 184, 182, 181, 32, 191, 128, 181, 180, 181, 187, 176, 33 ,0}; //Давление в линии упало ниже предела! (autogenerated by ru_str_converter.py script)
const char alrm14[] = {148, 176, 178, 187, 181, 189, 184, 181, 32, 178, 32, 187, 184, 189, 184, 184, 32, 178, 139, 136, 181, 32, 188, 184, 189, 184, 188, 131, 188, 176, 46 ,0}; //Давление в линии выше минимума. (autogenerated by ru_str_converter.py script)
const char alrm15[] = {173, 187, 181, 186, 130, 128, 184, 135, 181, 129, 186, 176, 143, 32, 129, 181, 130, 140, 32, 190, 130, 186, 187, 142, 135, 181, 189, 176, 33 ,0}; //Электрическая сеть отключена! (autogenerated by ru_str_converter.py script)
const char alrm16[] = {173, 187, 181, 186, 130, 128, 184, 135, 181, 129, 186, 176, 143, 32, 129, 181, 130, 140, 32, 191, 190, 180, 186, 187, 142, 135, 181, 189, 176, 46 ,0}; //Электрическая сеть подключена. (autogenerated by ru_str_converter.py script)
	
u8g_t ffont;

void DrawLog(void){	
	u8g_SetFont(&ffont, rus10x20);
	rus_font_color = WHITE_COLOR;
	FillBackground(MAIN_BGND);
	uint32_t here_max, here_addr;
	uint8_t uniq;
	if(LOG_FindMaxUnique(&here_max, &here_addr, &uniq)){
		LOG_Display(here_addr);
	}else{
		u8g_DrawStr(&ffont, 5, 15, no_logs);
	}	
}

void LOG_Display(uint32_t addr){
	uint16_t n = 19;
	LOG_ReadFlash(addr, read_buf, LOG_ENTRY_SIZE);
	u8g_DrawStr(&ffont, 5, n, header1);
	u8g_DrawStr(&ffont, 5, 2 * n, header2);
	u8g_DrawStr(&ffont, 5, 3 * n, header3);
	if(read_buf[2] & 0x80000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 4 * n, alrm1); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 4 * n, alrm2);} //battery out
	if(read_buf[2] & 0x40000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 5 * n, alrm3); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 5 * n, alrm4);} //concentrator max
	if(read_buf[2] & 0x20000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 6 * n, alrm5); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 6 * n, alrm6);} //concentrator unsofficient
	if(read_buf[2] & 0x10000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 7 * n, alrm7); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 7 * n, alrm8);} //cylinders empty
	if(read_buf[2] & 0x08000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 8 * n, alrm9); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 8 * n, alrm10);} //emergency
	if(read_buf[2] & 0x04000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 9 * n, alrm11); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 9 * n, alrm12);} //line max
	if(read_buf[2] & 0x02000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 10 * n, alrm13); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 10 * n, alrm14);} //line min
	if(read_buf[2] & 0x01000000) {rus_font_color = RED_COLOR; u8g_DrawStr(&ffont, 5, 11 * n, alrm15); }else {rus_font_color = WHITE_COLOR; u8g_DrawStr(&ffont, 5, 11 * n, alrm16);} //power off
}


	
