#include "u8g.h"
#include "rus4x6.h"
#include "rus10x20.h"

/*Employs u8g library. Some source files was rudely edited.
The list of edits is below:
u8g_IIapi.c 420 commented
from 421 till the end is a new function
41 #include "stm32_adafruit_lcd.h"
*/

u8g_t ffont;
#define LLN 21
const char sstr[LLN] = {158, 136, 184, 177, 186, 176, 32, 180, 176, 178, 187, 181, 189, 184, 143, 33 ,0}; //Ошибка давления! (autogenerated by ru_str_converter.py script)
	
void RusFontTry(void){
	u8g_SetFont(&ffont, rus10x20);
	u8g_DrawStr(&ffont, 280, 280, sstr);
}
